services:
  postgres:
    image: postgres:15-alpine
    container_name: ${PROYECT_NAME}-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: ${NODE_ENV}
        BACKEND_URL: ${BACKEND_URL}
        BACKEND_PORT: ${BACKEND_PORT}
    container_name: ${PROYECT_NAME}-${NODE_ENV}-backend
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      BACKEND_URL: ${BACKEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/packages/backend
    command: ["yarn", "dev"]
    depends_on:
      - postgres

  admin:
    build:
      context: ./packages/admin
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_ADMIN_URL: ${REACT_APP_ADMIN_URL}
        REACT_APP_ADMIN_PORT: ${REACT_APP_ADMIN_PORT}
        PORT: ${PORT}
    container_name: ${PROYECT_NAME}-${NODE_ENV}-admin
    env_file:
      - .env
    environment:
      NODE_ENV: development
      REACT_APP_ADMIN_URL: ${REACT_APP_ADMIN_URL}
      REACT_APP_ADMIN_PORT: ${REACT_APP_ADMIN_PORT}
      PORT: ${PORT}
    ports:
      - "${REACT_APP_ADMIN_PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app/packages/admin
    command: ["yarn", "dev"]
    depends_on:
      - backend

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.dev
      args:
        FRONTEND_URL: ${FRONTEND_URL}
        FRONTEND_PORT: ${FRONTEND_PORT}
    container_name: ${PROYECT_NAME}-${NODE_ENV}-frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:4321"
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_PORT: ${FRONTEND_PORT}
      HOST: "0.0.0.0"
    working_dir: /usr/src/app/packages/frontend
    command: ["yarn", "start"]
    volumes:
      - .:/usr/src/app

networks:
  nar-app-network:
    driver: bridge